set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.SendKeys "%{TAB}"
WScript.Sleep 20

WshShell.SendKeys "{TAB}"
WScript.Sleep 20
WshShell.SendKeys "{TAB}"
WScript.Sleep 20
WshShell.SendKeys "{TAB}"
WScript.Sleep 20
WshShell.SendKeys "{TAB}"
WScript.Sleep 20
WshShell.SendKeys "{TAB}"
WScript.Sleep 20
WshShell.SendKeys "{TAB}"
WScript.Sleep 20
WshShell.SendKeys "{TAB}"
WScript.Sleep 20
WshShell.SendKeys "{ENTER}"
WScript.Sleep 200
WshShell.SendKeys "{TAB}"
WScript.Sleep 20
WshShell.SendKeys "{TAB}"
WScript.Sleep 20
WshShell.SendKeys "{TAB}"
WScript.Sleep 20
WshShell.SendKeys "{TAB}"
WScript.Sleep 20
WshShell.SendKeys "{TAB}"
WScript.Sleep 20
WshShell.SendKeys "{TAB}"
WScript.Sleep 20
WshShell.SendKeys "{TAB}"
WScript.Sleep 20
WshShell.SendKeys "{TAB}"
WScript.Sleep 20
WshShell.SendKeys "{TAB}"
WScript.Sleep 20
WshShell.SendKeys "{TAB}"
WScript.Sleep 20
WshShell.SendKeys "{TAB}"
WScript.Sleep 20
WshShell.SendKeys "{TAB}"
WScript.Sleep 20
WshShell.SendKeys "{TAB}"
WScript.Sleep 20
WshShell.SendKeys "{TAB}"
WScript.Sleep 20
WshShell.SendKeys "{TAB}"
WScript.Sleep 20
WshShell.SendKeys "{TAB}"
WScript.Sleep 20
WshShell.SendKeys "{ENTER}"
WScript.Sleep 6000
